import turtle

turtle.circle(20)

turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.left(90)
turtle.forward(50)
turtle.backward(70)

turtle.penup()
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.pendown()
turtle.forward(40)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(10)
turtle.backward(50)
turtle.forward(15)
turtle.right(90)
turtle.forward(25)
turtle.backward(25)
turtle.left(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(25)
turtle.backward(25)
turtle.left(90)

turtle.penup()
turtle.forward(60)
turtle.pendown()
turtle.circle(20)
turtle.right(90)

turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.left(90)
turtle.backward(20)
turtle.forward(40)
turtle.backward(20)
turtle.right(90)
turtle.forward(15)

turtle.penup()
turtle.left(90)
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.left(90)
turtle.forward(30)
turtle.backward(40)
turtle.left(90)

turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(30)
turtle.right(90)
turtle.forward(15)
